package procesador;

public enum TipoToken {
	PUNTOYCOMA, NEWLINE, IF, SWITCH, CASE, BREAK, NEW, ARRAY, FUNCTION, DOCWRITE, VAR,
	PROMPT, RETURN, IDENTIFICADOR, ENTERO, OPARITMETICO,
	OPRELACIONAL, OPASIGNACION, OPESPECIAL,
	OPLOGICO, CORCHETEAB, CORCHETECE, PARENTESISAB,
	PARENTESISCE, LLAVEAB, LLAVECE, COMA, DOSPUNTOS,
	CADENA, EOF
}
