package procesador;

public enum TipoToken {
	PUNTOYCOMA, NEWLINE, PALABRACLAVE, 
	IDENTIFICADOR, ENTERO, OPARITMETICO,
	OPRELACIONAL, OPASIGNACION, OPESPECIAL,
	OPLOGICO, CORCHETEAB, CORCHETECE, PARENTESISAB,
	PARENTESISCE, LLAVEAB, LLAVECE, COMA, DOSPUNTOS,
	COMILLAS, EOF
}
